#pragma once

#ifndef __RPC_ENUMERATIONS_H
#define __RPC_ENUMERATIONS_H

namespace RPC
{
	enum {
		ClickPlayer = 23,
		ClientJoin = 25,
		EnterVehicle = 26,
		SelectPbject = 27,
		ScriptCash = 31,
		ServerCommand = 50,
		Spawn = 52,
		Death = 53,
		NPCJoin = 54,
		DialogResponse = 62,
		ClickTextDraw = 83,
		SCMEvent = 96,
		WeaponPickupDestroy = 97,
		Chat = 101,
		SrvNetStats = 102,
		ClientCheck = 103,
		DamageVehicle = 106,
		GiveTakeDamage = 115,
		EditAttachedObject = 116,
		EditObject = 117,
		SetInteriorID = 118,
		MapMarker = 119,
		RequestClass = 128,
		RequestSpawn = 129,
		ConnectionRejected = 130,
		PickedUpPickup = 131,
		MenuSelect = 132,
		VehicleDestroyed = 136,
		MenuQuit = 140,
		ExitVehicle = 154,
		UpdateScoresPingsIPs = 155,
		CamTargetUpdate = 168,
		GiveActorDamage = 177,
	};
};

namespace ScriptRPC
{
	enum {
		SetPlayerName = 11,
		SetPlayerPos = 12,
		SetPlayerPosFindZ = 13,
		SetPlayerHeath = 14,
		TogglePlayerControllable = 15,
		PlaySound = 16,
		SetPlayerWorldBounds = 17,
		GivePlayerMoney = 18,
		SetPlayerFacingAngle = 19,
		ResetPlayerMoney = 20,
		ResetPlayerWeapons = 21,
		GivePlayerWeapon = 22,
		SetVehicleParamsEx = 24,
		CancelEdit = 28,
		SetPlayerTime = 29,
		ToggleClock = 30,
		WorldPlayerAdd = 32,
		SetPlayerShopName = 33,
		SetPlayerSkillLevel = 34,
		SetPlayerDrunkLevel = 35,
		Create3DTextLabel = 36,
		DisableCheckpoint = 37,
		SetRaceCheckpoint = 38,
		DisableRaceCheckpoint = 39,
		GameModeRestart = 40,
		PlayAudioStream = 41,
		StopAudioStream = 42,
		RemoveBbuildingForPlayer = 43,
		CreateObject = 44,
		SetObjectPos = 45,
		SetObjectRot = 46,
		DestroyObject = 47,
		DeathMessage = 55,
		SetPlayerMapIcon = 56,
		RemoveVehicleComponent = 57,
		Destroy3DTextLabel = 58,
		ChatBubble = 59,
		SCMTimeUpdate = 60,
		ShowDialog = 61,
		DestroyPickup = 63,
		LinkVehicleToInterior = 65,
		SetPlayerArmour = 66,
		SetPlayerArmedWeapon = 67,
		SetSpawnInfo = 68,
		SetPlayerTeam = 69,
		PutPlayerInVehicle = 70,
		RemovePlayerFromVehicle = 71,
		SetPlayerColor = 72,
		DisplayGameText = 73,
		ForceClassSelection = 74,
		AttachObjectToPlayer = 75,
		InitMenu = 76,
		ShowMenu = 77,
		HideMenu = 78,
		CreateExplosion = 79,
		ShowPlayerNameTagForPlayer = 80,
		AttachCameraToObject = 81,
		InterpolateCamera = 82,
		SetObjectMaterial = 84,
		GangZoneStopFlash = 85,
		ApplyAnimation = 86,
		ClearAnimations = 87,
		SetPlayerSpecialActor = 88,
		SetPlayerFightingStyle = 89,
		SetPlayerVelocity = 90,
		SetVehicleVelocity = 91,
		SetPlayerDrunkVisuals = 92,
		ClientMessage = 93,
		SetWorldTime = 94,
		CreatePickup = 95,
		SetVehicleTires = 98,
		MoveObject = 99,
		EnableStuntBonusForPlayer = 104,
		TextDrawSetString = 105,
		SetCheckpoint = 107,
		GangZoneCreate = 108,
		ToggleWideScreen = 111,
		PlayCrimeReport = 112,
		SetPlayerAttachedObject = 113,
		GangZoneDestroy = 120,
		GangZoneFlash = 121,
		StopObject = 122,
		SetNumberPlate = 123,
		TogglePlayerSpectating = 124,
		PlayerSpectatePlayer = 126,
		PlayerSpectateVehicle = 127,
		SetPlayerWantedLevel = 133,
		ShowTextDraw = 134,
		TextDrawHideForPlayer = 135,
		ServerJoin = 137,
		ServerQuit = 138,
		InitGame = 139,
		RemovePlayerMapIcon = 144,
		SetPlayerAmmo = 145,
		SetGravity = 146,
		SetVehicleHealth = 147,
		AttachTrailerToVehicle = 148,
		DeattachTrailerFromVehicle = 149,
		SetPlayerDrunkHandling = 150,
		DestroyWeaponPickup = 151,
		SetWeather = 152,
		SetPlayerSkin = 153,
		SetPlayerInterior = 156,
		SetPlayerCameraPos = 157,
		SetPlayerCameraLookAt = 158,
		SetVehiclePos = 159,
		SetVehicleZAngle = 160,
		SetVehicleParamsForPlayer = 161,
		SetCameraBehindPlayer = 162,
		WorldPlayerRemove = 163,
		WorldVehicleAdd = 164,
		WorldVehicleRemove = 165,
		WorldPlayerDeath = 166,
		DisableVehicleCollisions = 167,
		SetPlayerObjectNoCamCol = 169,
		ToggleCameraTarget = 170,
		CreateActor = 171,
		DestroyActor = 172,
		ApplyActorAnimation = 173,
		ClearActorAnimation = 174,
		SetActorRotation = 175,
		SetActorPosition = 176,
		SetActorHealth = 178
	};

};


#endif
